version: '3.1'

services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:1.14.0
    ports:
      - "8001:8001"
    volumes:
      - ./redisinsight:/db

  mongo:
    image: mongo
    container_name: mongo_container
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: NoSql
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  mariadb:
    image: mariadb
    container_name: mariadb_container
    restart: always
    environment:
      MARIADB_ROOT_PASSWORD: example
      MARIADB_DATABASE: user
      MARIADB_USER: example
      MARIADB_PASSWORD: password
    ports:
      - "3307:3306"
    volumes:
      - mariadb-data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - 7687:7687
      - 7474:7474
    volumes:
      - data:/data

volumes:
  mongo-data:
  redisinsight:
  mariadb-data:
  data:
